README.md
=> docs(readme): add GitHub token scope notes

bin/semantic-release.js, tests/scenarios/verify.js
aka `v0.0.0-semantically-released`
=> Not publishing placeholder versions

lib/npm-info.js, package.json, tests/.npmrc, tests/index.js, tests/tap/npm-info.js
Hi @boennemann,
this pull request should close #28. :relaxed:
=> feat(npm-info): support private modules

README.md
I just ran into this twice with a new repository so this _might_ be a helpful note :)
=> docs(readme): Reminder to enable Travis to make encrypt work

README.md
=> docs(README): fix mistake in headline

package.json
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
=> Updated coveralls to version 2.11.4

package.json
:rocket:
nock just published version 2.13.0, so that’s now up to date in your `package.json`.
Check that it doesn’t break your code and release the new version of your software safe in the knowledge that it will stay in this working state.
---
The new version differs by 11 commits (ahead by 11, behind by 0).
- [53388e8](https://github.com/pgte/nock/commit/53388e873321c126613a1f56eff871158105173b): v2.13.0
- [7635ca6](https://github.com/pgte/nock/commit/7635ca63444a9390f3eb544004e04ddf7901f338): Merge branch 'jshcrowthe-master'
- [d5272f3](https://github.com/pgte/nock/commit/d5272f324c9875d5501457e3aa0ad9e5524a0b8d): Remove throw error statement from test (copy paste error)
- [87367c6](https://github.com/pgte/nock/commit/87367c6559d5c1d5398fd6d8f9ce58fc922ece14): Test wording change
- …
=> Updated nock to version 2.13.0

package.json, src/index.js
Part of #104.
Which test file should I modify to add tests for this?
It currently passes on my machine,
=> Use normalize-package-metadata to normalize package.json info

bin/semantic-release.js
=> fix: only ever change version field in published package.json

README.md, TROUBLESHOOTING.md
Starting a library of common issues with semantic-release and how to recover.
=> Add troubleshooting guide to README

bin/semantic-release.js, test/integration.test.js
Fix regression introduced in #451
=> Exit with 1 if unexpected error happens

package.json, src/lib/get-commits.js, src/lib/get-version-head.js, src/lib/logger.js, test/helpers/git-utils.js, test/helpers/mock-github.js, test/helpers/mockserver.js, test/integration.test.js
=> Update prettier to the latest version 🚀

.travis.yml, index.js, lib/get-commits.js, lib/get-next-version.js, lib/plugins/definitions.js, lib/plugins/normalize.js, package.json, test/get-commits.test.js, test/get-next-version.test.js, test/git.test.js, test/helpers/mockserver.js, test/helpers/npm-registry.js, test/index.test.js, test/integration.test.js, test/plugins/definitions.test.js, test/plugins/normalize.test.js, test/plugins/pipeline.test.js, test/plugins/plugins.test.js
Fix a few typos in doc and log messages.
Minor improvement in tests and a few additional tests.
All the details should be in the commits messages.
=> Various fixes

lib/plugins/normalize.js, test/plugins/normalize.test.js
=> Log plugin type in addition of path

package.json
=> Update @semantic-release/github to version 2.2.3

.travis.yml
=> Fix travis-deploy-once install cmd

package.json, test/integration.test.js
=> Update @semantic-release/github to the latest version 🚀

package.json
The marked dependency has a known moderate severity security vulnerability in version range < 0.3.9 and should be updated.
=> fix(security): Updated marked dependency

book.json, docs/recipes/gitlab-ci.md, docs/support/FAQ.md, docs/support/troubleshooting.md, docs/usage/installation.md
- Add anchor links to heading
- Refactor the troubleshooting guide
- fix typo per comments in #593
=> Doc update

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATES/bug-report.md, .github/ISSUE_TEMPLATES/feature-request.md, .github/ISSUE_TEMPLATES/plugin-request.md, CONTRIBUTING.md
=> Contributing guidelines and issue template

package.json
=> fix(package): update lodash to version 4.17.4

docs/usage/ci-configuration.md
=> Fix image path

cli.js, docs/usage/configuration.md, index.js, lib/get-config.js, lib/get-last-release.js, lib/git.js, lib/plugins/index.js, lib/verify.js, test/get-config.test.js, test/get-last-release.test.js, test/git.test.js, test/index.test.js, test/plugins/plugins.test.js, test/verify.test.js
=>  feat: add `tagFormat` option to customize Git tag name

lib/git.js
Fixes https://github.com/semantic-release/semantic-release/issues/629
=> fix: use long option to delete tag in git push

package.json
=> fix(package): update @semantic-release/github to version 4.0.2

package.json, test/get-git-auth-url.test.js
=>  fix(package): update git-url-parse to version 8.1.0

lib/get-config.js, lib/git.js, test/git.test.js
Since #623, it's now safe to log more debug info. That would help troubleshooting git related issues such as #643.
=> feat: add debug logs for git commands

CONTRIBUTING.md, README.md
Made some grammar/spelling changes to the README.md and CONTRIBUTING.md.  Addresses some points brought up in #653.
=> docs: make some grammar, typo fixes 

docs/recipes/circleci-workflows.md, docs/recipes/gitlab-ci.md, docs/recipes/travis-build-stages.md, docs/recipes/travis.md
=> Add Travis Build Stages and CircleCI recipes

lib/get-config.js, lib/git.js, test/integration.test.js
=>  fix: convert `git+https` URL in package.json to `https`

index.js, lib/git.js
Per https://github.com/semantic-release/semantic-release/issues/699#issuecomment-373445979
=> fix: prevent git CLI to prompt user/password on CI

lib/get-last-release.js, test/get-last-release.test.js
=> fix: handle case with no last release in history

index.js, lib/git.js, test/get-git-auth-url.test.js, test/git.test.js, test/helpers/git-utils.js, test/index.test.js
=> fix: verify the local branch is up to date with the remote one

lib/get-git-auth-url.js
=> fix: fix Bitbucket authenticated URL

docs/usage/ci-configuration.md, lib/get-git-auth-url.js, test/get-git-auth-url.test.js
Ref https://github.com/semantic-release/semantic-release/pull/767#issuecomment-385682320
=> feat: add support for Bitbucket token in environment variables

.travis.yml
@gr2m should we test on Node 8 and 10 only or on 9 only?
=> ci: run test on Node.js 10

docs/recipes/git-auth-ssh-keys.md
=> docs: add comment about publishing with ssh keys

lib/git.js, test/git.test.js
Cherry picked commit from #725 and added missing test.
Fix #725
=> fix: correct `git merge-base` error code handling

docs/usage/configuration.md, index.js, lib/definitions/constants.js, lib/definitions/errors.js, lib/definitions/plugins.js, lib/definitions/release-types.js, lib/get-next-version.js, test/index.test.js
Use [Git Environment Variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#Committing). Set default values if environement variables are not set.
See semantic-release/git#47
=> feat: set tag author and committer name/email

README.md, docs/support/FAQ.md
=> docs: clarify which commit types trigger a release

bin/semantic-release.js, lib/git.js, package.json
=> feat: verify minimum required git version is installed

docs/extending/plugins-list.md
https://github.com/raix/semantic-release-vsce
=> docs(plugins): add semantic-release-vsce

docs/usage/plugins.md
`verifyConditions` explanation was wrong previously.
=> Fix documented explanation in plugins.md

index.js, lib/git.js, test/git.test.js, test/helpers/git-utils.js, test/index.test.js, test/integration.test.js
=>  fix: fetch all tags even if the repo is not shallow

index.js
=> fix: do not override env variable with default if defined

package.json
=> Update @semantic-release/npm to the latest version 🚀

lib/get-git-auth-url.js, test/get-git-auth-url.test.js
=> fix: do not convert ssh `repositoryUrl` to https

lib/get-git-auth-url.js, test/get-git-auth-url.test.js
=> Revert "fix: do not convert ssh `repositoryUrl` to https"

cli.js, test/cli.test.js
=> fix: support multiple generate-notes plugin in CLI arg

docs/support/troubleshooting.md, docs/usage/configuration.md
=> Add troubleshooting docs and a section about existing tags

index.js
=> feat: Return release notes on nextRelease even if running on dry mode

index.js, lib/definitions/plugins.js, lib/get-last-release.js, lib/git.js, test/cli.test.js, test/git.test.js, test/helpers/git-utils.js, test/integration.test.js, test/verify.test.js
I made several minor refactoring / typo fix in #991.
For clarity I moved them in their own commits.
=> Minor refactoring and typos

lib/git.js, test/git.test.js
=> fix: push only tags to remote repo

docs/extending/plugins-list.md
=> docs: add maven-semantic-release to list of community plugins

cli.js, docs/usage/configuration.md, lib/get-config.js, test/cli.test.js, test/get-config.test.js
=>  fix: allow to set `ci` option via API and config file

lib/definitions/plugins.js, test/index.test.js
Fix semantic-release/github#139
=> fix: correctly handle skipped releases

lib/utils.js, test/utils.test.js
Fix semantic-release/semantic-release#1038
=> fix: fix range regexp to handle version with multiple digits

lib/get-next-version.js, test/get-next-version.test.js
=> fix: correctly determine next pre-release version

docs/recipes/git-auth-ssh-keys.md
Hello folks 👋 
I have corrected a little mistake in the example to add a ssh key for circleCi.
Good work on this package, keep on !
=> docs(circle): fix incorrect script example

docs/developer-guide/js-api.md, docs/recipes/distribution-channels.md, docs/recipes/maintenance-releases.md, docs/recipes/pre-releases.md, docs/usage/configuration.md, docs/usage/workflow-configuration.md, lib/get-config.js, package.json, test/branches/expand.test.js, test/get-config.test.js, test/index.test.js
=> fix: fix maintenance branch regex

README.md
=> docs: Remove broken waffle.io 💀 badge

docs/extending/plugins-list.md, docs/usage/plugins.md
=> doc: add info about default plugis

index.js, lib/branches/expand.js, lib/branches/index.js, lib/git.js, test/branches/branches.test.js, test/branches/expand.test.js, test/git.test.js, test/index.test.js
Fixing issue with authentication for repositoryUrl not being used for prerelease workflow
=> fix(repositoryUrl): on beta repositoryUrl needs auth for pre-release flows

index.js, lib/definitions/constants.js, lib/git.js, test/git.test.js, test/helpers/git-utils.js
=> feat: create annotated tags

docs/usage/plugins.md
=> fix typo in plugins.md file

.travis.yml
Added node 12 and set node 8 to node 8.3 for travis. 
This should close #1224
=> ci(node): set node 8 to 8.3 and add node 12

docs/03-recipes/circleci-workflows.md
* Remove extra `01-` and add new specific anchor link.
👋 Hi, hopefully it helps the next folk 😄
=> docs: update semantic-release-cli broken link

docs/01-usage/getting-started.md
=> docs: tried to fix #1250

bin/semantic-release.js, lib/definitions/errors.js
This PR will
- fix the documentation links to this repository by adding the appropriate numbers
=> fix(definitions): Repository documentation links

lib/definitions/errors.js
=> fix: clarify message for EGITNOPERMISSION error

docs/usage/configuration.md, test/helpers/gitbox.js
=> docs: typo is link to workflow config

lib/get-git-auth-url.js, test/get-git-auth-url.test.js
=> fix: ignore custom port when converting ssh repo URL to https

index.js, lib/git.js, test/git.test.js
=> fix: use authenticated URL to check if local branch is up to date

lib/branches/get-tags.js
=> fix: simplify `get-tags` algorithm

docs/usage/workflow-configuration.md, lib/get-last-release.js, lib/get-next-version.js, lib/utils.js, test/index.test.js, test/utils.test.js
=> fix: allow multiple branches with same channel

package.json
This reverts commit 8d8910577f0702087684e360e3c92ee6cc5793a0.
=> revert: fix: update commit-analyzer dep version off errant publish

docs/recipes/gitlab-ci.md
=> docs: clarify GitLab CI/CD protected variable usage

docs/usage/workflow-configuration.md, lib/branches/normalize.js, test/branches/branches.test.js, test/branches/normalize.test.js, test/index.test.js
=> feat: allow to release any version on a branch if up to date with next branch

index.js, lib/git.js, test/git.test.js, test/index.test.js
=> fix: verify is branch is up to date by comparing remote and local HEAD

lib/get-next-version.js, test/get-next-version.test.js
=> fix: look also for previous prerelease versions to determine the next one

docs/usage/plugins.md
Per https://github.com/semantic-release/semantic-release/issues/653#issuecomment-574562680
=> docs: correct plugin execution order

lib/git.js, test/git.test.js, test/helpers/git-utils.js
Fix #1410 
Tentative fix for #1410. Will do more test before merging to avoid regression on other CI.
=> fix: fetch tags on repo cached by the CI

docs/recipes/travis.md
If you want to have more prereleases than default so you have to enable deploy on all branches. ref.: https://docs.travis-ci.com/user/deployment#examples-of-conditional-deployment
=> docs(travis): build on all branches by default

docs/recipes/pre-releases.md
fix a little typo: fist -> first
=> docs: fix typo

package.json
=> Update marked-terminal to v4

docs/usage/getting-started.md
Resolves following incorrectly formatted numbered list:
=> Docs: Fixes incorrect formatting

cli.js, index.js, lib/branches/index.js, lib/definitions/errors.js, lib/definitions/plugins.js, lib/get-config.js, lib/git.js, lib/plugins/index.js, lib/utils.js, package.json, test/cli.test.js, test/git.test.js, test/helpers/git-utils.js, test/plugins/pipeline.test.js
=> chore(package): update xo to version 0.28.1

lib/utils.js, package.json, test/utils.test.js
See https://github.com/npm/node-semver/issues/322, closes #1524
=> fix: adapt for semver v7.3.2

lib/utils.js, test/utils.test.js
follow up for https://github.com/semantic-release/semantic-release/commit/0363790b8a5f91a8c95fc6905e3e20305db7c539\#r38547135
=> fix: adapt for semver to version 7.3.2 (part II)

docs/recipes/gitlab-ci.md
Signed-off-by: solidnerd <niclas@mietz.io>
=> docs: update recipe for gitlab-ci with Node.js >=10.18

docs/usage/getting-started.md
I personally feel this is easier and doesn't leave any traces on my system.
=> docs: Recommend using npx instead of installing globally

docs/recipes/README.md, docs/recipes/jenkins-ci.md
As discussed in #1586 
I have created this pull request to add a recipe for Jenkins CI configuration for Semantic release. ( https://semantic-release.gitbook.io/semantic-release/recipes/recipes )
Fixes #1586
=> docs: added recipe for Jenkins CI configuration (#1)

docs/support/resources.md
This is a complete series about semantic release package and how to use it. in this series i explained what is semantic version and how to automate it using semantic release package along with Github actions and publish the package using GitHub packages and finally deploy to Github pages.
=> docs(resources.md): added more sematnic release article

docs/recipes/github-actions.md
cf. https://github.com/actions/checkout
=> docs(github-actions): use actions/checkout@v2

docs/recipes/github-actions.md
This PR should add to the docs about the issue that is linked: fixes https://github.com/semantic-release/semantic-release/issues/1625.
=> docs: improve github actions recipe on git plugin

docs/recipes/github-actions.md
see https://github.com/semantic-release/npm/issues/277
=> docs: note that publish token is required

docs/extending/plugins-list.md
documentation for semantic-release-pypi plugin
=> docs: add semantic-release-pypi plugin

docs/recipes/github-actions.md
=> docs: fix a typo in github-actions.md

README.md
=> docs(discussions): updated spectrum references to point to discussions instead

docs/extending/plugins-list.md
Hi there
I've made this plugin to automatically open a pull request with assets update on github after a release.
Thank you
=> docs: add semantic-release-github-pullrequest to list of community plugins

package-lock.json, package.json
=> fix(deps): peer dependecy error with `marked-terminal`

lib/git.js
Update addNote function documentation
fixes #1634
=> Update addNote function documentation

docs/recipes/github-actions.md
instead of a concrete version of Ubuntu
=> docs(github-actions): example suggests using ubuntu-latest

docs/developer-guide/plugin.md
This commit will improve the following in the Plugin developer guide:
* Lifecyle list more complete (previous was missing some lifecycles)
* Context object has been now described in more detail per lifecycle
* Some readability/maintainability fixes to the markdown file itself
to make it easier to edit and read in an editor.
=> docs(Plugin Developer Guide): More detailed lifecycle list and context descriptions

docs/recipes/distribution-channels.md
If I understand correctly, I believe that this correction is valid, otherwise please disregard this PR.
=> docs(distribution-channels): fix branch name

docs/extending/plugins-list.md
The plugin can assist in deploying Heroku apps.
=> docs: add heroku to list of community plugins

docs/extending/plugins-list.md
The plugin will send notifications to the telegram chats
=> docs: add semantic-release-telegram to the list of community plugins

README.md
fixes #1960
- Improve sentence
The previous sentence was OK, but I think it can be improved a bit.
=> docs(README): improve sentence

docs/recipes/maintenance-releases.md
**This PR**
* fixes some minor typos in the recipe for maintenance releases.
Signed-off-by: Moritz Wiesinger <moritz.wiesinger@dynatrace.com>
=> docs(recipes): fix some typos in maintenance releases recipe

docs/recipes/github-actions.md
- Update `actions/setup-node@v1` -> `actions/setup-node@v2`
- Change `node-version: '14.17'` -> `node-version: 'lts/*'`
Fixes #2140
=> docs(github-actions): update workflow version, update node-version

docs/extending/plugins-list.md
Adding https://github.com/eshepelyuk/semantic-release-helm-oci
=> docs(plugins): add @eshepelyuk/semantic-release-helm-oci to plugins list

package-lock.json, package.json
Reverts semantic-release/semantic-release#2229
=> Revert "chore(deps): update dependency p-retry to v5"

SUMMARY.md, docs/recipes/README.md
based on https://docs.gitbook.com/integrations/git-sync/faq#nothing-happens-on-gitbook-after-adding-a-new-file-to-my-repository
=> docs(gitbook): updated the summary document so that missing pages are rendered by gitbook

README.md
* also removes link to unknown “package managers and languages” recipes
=> docs(recipes): fix path to recipes

CONTRIBUTING.md
and broke lines after sentences
=> docs(issue-templates): fixed links to templates for opening issues

README.md
=> docs(badge): mentioned referencing the commit convention

docs/usage/ci-configuration.md
Fixes a broken link to the CI configuration recipes.
=> docs: fix a broken link

lib/branches/index.js, lib/definitions/branches.js, lib/get-git-auth-url.js, lib/git.js, package.json, test/definitions/branches.test.js, test/helpers/mockserver.js, test/helpers/npm-registry.js
the performance and readability of reduce is not a concern in this project since maintainers are
familiar with the idiom and are iterating over small lists. the filter rule is disabled selectively
since the filter being identified is not Array.filter
closes #2403
=> chore(lint): disabled rules that dont apply to this project

docs/extending/plugins-list.md
A new plugin for React Native versioning.
=> docs: add semantic-release-react-native to plugin list

package-lock.json, package.json
Reverts semantic-release/semantic-release#1912, fixes #2533
=> Revert "fix(deps): update dependency yargs to v17"

test/helpers/mockserver.js
=> test(mockserver): switched to the modern mockserver/mockserver image to get multi-arch support

docs/usage/workflow-configuration.md
A correct english sentence needs a verb, which is "be" in this case
=> docs(workflow-configuration): improved sentence structure

index.d.ts, package.json
These type definitions are feature complete and include all of the interfaces, options and callbacks from the main semantic-release package.
=> feat: Added TypeScript definitions

.github/workflows/test.yml
for #semantic-release/.github#19
=> ci(matrix): prevent skipping the test job when test_matrix fails

docs/extending/plugins-list.md
=> docs: add community plugin `semantic-release-pub`

package-lock.json, package.json
=> fix: Revert "fix(deps): update dependency cosmiconfig to v9"

docs/extending/plugins-list.md
Close https://github.com/semantic-release/semantic-release/issues/3231
=> docs: add community plugin semantic-release-hackage

docs/recipes/ci-configurations/github-actions.md, docs/support/FAQ.md
this is an overdue update to make our recommendation more clear/official
=> docs(release-commits): clarify our recommendation to avoid commits within the FAQs

README.md
This PR updates the CI build status badge.
=> doc(README): fix CI status badge

docs/extending/plugins-list.md
This plugin analyzes commit messages by [commitlint](https://github.com/conventional-changelog/commitlint)
=> docs(plugins): community plugin `semantic-release-commits-lint`

package-lock.json, package.json
This PR removes `codecov` from the project following the notice from @tidelift on its cease of support.
Related to #3425
=> test: remove `codecov`

lib/utils.js, test/definitions/branches.test.js
=> fix: regex to identify maintenance branches

lib/get-git-auth-url.js
Provides a timestamped log entry for this process so it's clear how long this took to complete.
=> fix(get-git-auth-url.js): Added debug for success

.github/ISSUE_TEMPLATE/01_bug_report.yml, .github/ISSUE_TEMPLATE/02_feature_request.yml, .github/ISSUE_TEMPLATE/03_plugin_suggestion.yml
This will automatically apply existing labels.
=> Use labels in issue templates

index.d.ts, package-lock.json, package.json
BaseContext was missing options key with the `Options` object
Fixes #3601
=> Fixed typescript definition

docs/extending/plugins-list.md
Closes  https://github.com/semantic-release/semantic-release/issues/3788
=> docs(plugin): add semantic-release-skopeo to plugins-list.md
