semantic-release/semantic-release

- README.md
I think it'd be more prominent if we had the note inside the example .travis.yml instead of at the bottom.
This is a super important thing to have, as without travis-after-all, you get into a whole host of issues with publishing.
> docs(readme): add travis-after-all note to example .travis.yml

- .travis.yml
This PR adds Node.js v4 (LTS version `argon`) and v5 (latest stable version) to the tested Node.js versions.
> Run Travis tests under Node.js v4 (argon) and v5 (latest)

- README.md
- src/lib/verify.js
- src/post.js
- test/specs/verify.js
- Adds GitHub enterprise support by adding a `githubApiPathPrefix` option to the configuration to be passed to `node-github`, given that Enterprise APIs have a `/api/v3/` prefix.
- Removes checking of the repository URL in `package.json` as per @boennemann's suggestion in #146 to allow for custom git URLs
Tested with both GitHub and GitHub Enterprise. 
closes #146
> feat(post): Adds GitHub Enterprise support

- README.md
The conventions have been split off in ajoslin/conventional-changelog@48580b039197f45574f309b1c2ade18c17c2933b
One could also link to the pinned version, https://github.com/stevemao/conventional-changelog-angular/blob/f07464cd7577e3c0aab9d400e9ca8da219603bba/convention.md
> Fix link to explanation of commit message format

- bin/semantic-release.js
Exposing this allows semantic-release to be used in environments with self-signed certificates.  See also: https://github.com/semantic-release/last-release-npm/pull/75
> Expose cafile from npm config

- src/lib/commits.js
- test/mocks/child-process.js
This fixes issue #286. This is needed for repositories with a lot of commits and/or a big changelog.
To get green:
> fix(gitlog): increase maxBuffer

- src/lib/commits.js
Running `semantic-release` fails locally if/when `git branch` produces colored output. This PR simply adds `--no-color` to the executed command. With this fix I get the next version correctly, while previously I would get an `ENOTINHISTORY`-error, since the check does not anticipate color codes in the branch names.
| Before | After |
| ------ | ----- |
| ![1____project_stylizr__bash_](https://cloud.githubusercontent.com/assets/463105/20482660/11cb543e-afee-11e6-8dbc-29e3de3df66e.jpg) | ![1____project_stylizr__bash_](https://cloud.githubusercontent.com/assets/463105/20482649/08b5807c-afee-11e6-8cbe-17675be80b66.jpg) |
> fix(commits): Use `--no-color` for `git branch`-command

- package.json
- src/lib/commits.js
- test/mocks/child-process.js
Related to https://github.com/semantic-release/semantic-release/issues/286
Uses `child_process.spawn` instead of `child_process.exec`, as `exec` has a fixed `maxBuffer`.
Only converted `git log` to use the new `spawn` method to reduce PR complexity and `git log` seems like the main culprit for `maxBuffer` errors.
> fix: use spawn instead of exec for 'git log' to avoid maxBuffer err

- package.json
I noticed your (hilarious) branch names! And also that the `home` link is old and points to a non-existent branch. ✨
> Fix 'home' link in package.json

- src/post.js
- test/mocks/github.js
- test/specs/post.js
GitHub Releases has an awesome feature that shows how many commits are created since the release.
Example: [github/hub releases](https://github.com/github/hub/releases)
However, the project which uses semantic-release seems to not to have this awesomeness.
Example: [semantic-release/semantic-release releases](https://github.com/semantic-release/semantic-release/releases)
`target_commitish` in GitHub Releases has two different meanings:
* Target commit that a new associated tag will be created on
* Target branch to compute how many "commits to since this release"
`target_commitish` is usually the default branch (aka `master`), because the
distance between the release and the latest branch is the primary concern.
Before this change, `target_commitish` was left to be a hash and the
feature …
> Get "## commits to master since this release" working

- src/post.js
Fixes #415, introduced in #335.
I checked any branches will not be created in the following sandbox repository.
https://github.com/umireon/semantic-release-sandbox-target-committish/releases/tag/v1.0.13
> fix(post): create git tag properly

- README.md
[validate-commit-msg](https://github.com/kentcdodds/validate-commit-msg) is deprecated, and points to [commitlint](https://github.com/marionebl/commitlint).
> Update commit lint suggestion

- package.json
Use of `czConfig` is deprecated, now it's `config.commitizen`
Docs state as well that (since recently?) they support lookup in `node_modules`.
[Relevant `commitizen` docs](https://github.com/commitizen/cz-cli#commitizen-for-project-maintainers)
> Update commitizen config

- README.md
Just a small fix to make this sentence parse.
> docs: fix grammatical error in README

- codecov.yml
Codecove should determine the default branch based on Github config but it doesn't seems to work.
Set in codecov.yml until it's fixed
> Set default branch in codecov.yml

- .travis.yml
- src/lib/get-commits.js
- src/lib/get-version-head.js
- test/get-commits.test.js
- test/helpers/git-utils.js
- test/integration.test.js
Add several fixes and improvements in the identification of the last release gitHead:
- If there is no last release, unshallow the repo in order to retrieve all existing commits
- If git head is not present in last release, try to retrieve it from git tag with format 'v\<version\>' or '\<version\>'
- If the last release git head cannot be determined and  found in commit history, unshallow the repo and try again
- Throw a ENOGITHEAD error if the gitHead for the last release cannot be found in the npm metadata nor in the git tags, preventing to make release based on the all the commits in the repo as before
- Add integration test for the scenario with a packed repo from which `npm republish` fails to read the git head
Fix #447, Fix #393, Fix #280, Fix #276, Fix #256, Fix #229, Fix #200
Note …
> Retrieve version gitHead from git tags and unshallow the repo if necessary

- src/lib/get-commits.js
- src/lib/get-version-head.js
- test/get-commits.test.js
- test/helpers/git-utils.js
- test/integration.test.js
- Tag sha will now be used also if there is a gitHead in last release and it's not in the history
- Use `git merge-base` to determine if a commit is in history, allowing to use CI creating detached head repo (Jenkins, Bitrise, ...)
- Mention recovery solution by creating a version tag in `ENOTINHISTORY` and `ENOGITHEAD` error messages
- Do not mention branches containing missing commit in `ENOTINHISTORY` and `ENOGITHEAD` error messages as it's not available by default on most CI
See discussion in #453.
In `ENOTINHISTORY` and `ENOGITHEAD` error messages I don't display the list of branches that contains the missing commit anymore. Most CI do not pull the other branches, so almost all the time those were not display anyway.
Adding this info in the logs would require to run
```bash
git …
```
> Allow to recover from ENOTINHISTORY with a tag and handle detached head repo

- src/index.js
- src/lib/plugins.js
- src/pre.js
- test/pre.test.js
The plugin module for `verifyConditions` and `verifyRelease` was returning:
- A `Promise` returning function if multiple plugins are defined
- The plugin itself (a function with callback) when there is only one plugin in the chain
The rest of the code expected `verifyConditions` and `verifyRelease` to be a function with callback and was promisifying it.
If there was multiple plugins in the pipeline that that was resulting in promisifying a promise and the errors returned were not caught and node was warning with ` UnhandledPromiseRejectionWarning: Unhandled promise rejection`.
With this fix the plugin module always return a `Promise` returning function for `verifyConditions` and `verifyRelease` and the rest of the code doesn't promisify them anymore.
See #406
> Handle errors when verifyConditions and verifyRelease are a pipeline

- bin/semantic-release.js
I found the CLI extremely hard to use when writing custom plugins, and debugging various access errors when running it on our internal CI servers instead of Travis.
I will therefore propose to output error information when unexpected errors (non `@semantic-release/error`) occur, instead of exiting silently.
For example:
```json
{
"release": { "verifyConditions": "./some-non-existing-file" }
}
```
Caused me a lot of grief, and I could not figure out why nothing happened.
> Add error messages for unknown rejections

- package.json
- src/cli.js
- src/lib/logger.js
- test/fixtures/plugin-error-a.js
- test/fixtures/plugin-error-inherited.js
- test/integration.test.js
- test/logger.test.js
- test/verify-pkg.test.js
`semantic-release` now log all information included in unexpected errors.
In order to verify if an error is a `SemanticReleaseError` we now use the `name` property rather than the instance type. The test will work properly if a plugin use a different version of `@semantic-release/error` than `semantic-release`.
We should probably deprecate all version of `@semantic-release/error` < 2.0.1 as it contains a bug that prevent the name and stacktrace to be included. See https://github.com/semantic-release/error/pull/71.
See https://github.com/semantic-release/semantic-release/pull/480#pullrequestreview-72660167
cc /@felixfbecker
> Log error properties and check SemanticReleaseError with name

- bin/semantic-release.js
- lib/get-next-version.js
- lib/plugins/definitions.js
- package.json
- test/get-commits.test.js
- test/git.test.js
- test/helpers/git-utils.js
- test/helpers/mock-github.js
- test/integration.test.js
- test/plugins/normalize.test.js
Making a lot of modification in `semantic-release` I grew increasingly frustrated with `eslint-config-standard` as `standard` disable many checks for common mistakes.
Here is a few examples (among many other instances) encountered across the `semantic-release` repos:
- Enforce using radix in parseInt() => [example](https://github.com/semantic-release/npm/pull/1#discussion_r149567842)
- Avoid negated conditions => [example](https://github.com/semantic-release/npm/pull/1#discussion_r149568538) and [example](https://github.com/semantic-release/npm/pull/1#discussion_r149568678)
- Use `const` or `let` instead of `var`
- Use `const` instead of `let` when possible => [example](https://github.com/semantic-release/semantic-release/compare/xo?expand=1#diff-3e42fed5223348e612fea401149a0b8eR77)
- …
> Lint with XO

- lib/plugins/definitions.js
- lib/plugins/index.js
- test/plugins/plugins.test.js
Fix regression introduced in #515
The configuration is now using the default plugin '@semantic-release/commit-analyzer' with passing a parameter instead of throwing an error.
```json
"release": {
"analyzeCommits": {
"param": "value"
}
}
```
> Use default plugin if the path property is missing from a single plugin configuration

- README.md
- cli.js
- index.js
- lib/get-config.js
- lib/git.js
- lib/plugins/normalize.js
- package.json
- test/fixtures/multi-plugin.js
- test/fixtures/plugin-error-inherited.js
- test/fixtures/plugin-error.js
- test/fixtures/plugin-noop.js
- test/fixtures/plugin-result-config.js
- test/get-config.test.js
- test/git.test.js
- test/helpers/git-utils.js
- test/index.test.js
- test/integration.test.js
- test/plugins/normalize.test.js
The last language specific thing `semantic-release` relies on is the `package.json`.
This PR remove this reliance by allowing to configure `semantic-release` with rc files in addition of the current `release` property in the `package.json`.
This way, with the proper plugins, `semantic-release` can release any type of project.
We should now recommend to install `semantic-release` globally:
```
npm install semantic-release -g
semantic-release
```
or with `npx`
```
npx semantic-release
```
or in Unix based CI:
```
if [[ `node -v | egrep -o '[0-9|\.]+'` > 8* ]]; then npm install semantic-release -g && semantic-release; fi
```
Here is the list of changes:
- Do not rely on `package.json` anymore
- Use `cosmiconfig` to load the configation. `semantic-release` can be configured:
- via CLI options …
> Make semantic-release language agnostic

- README.md
Add a _Node Support Policy_ section to the project's `README.md` file
to indicate what this project, and its core team, are promising in terms
of Node runtime support.
Establishing a support policy provides reassurance to the community that
they can expect a level of functionality from `semantic-release`, while
providing guidance to the core maintainers, and everyone else that
contributes, the level of support they should espire to.
Closes #485
> docs(README): add node support policy

- README.md
- cli.js
- index.js
- lib/get-config.js
- lib/git.js
- lib/plugins/index.js
- lib/plugins/normalize.js
- package.json
- test/fixtures/index.js
- test/get-config.test.js
- test/git.test.js
- test/index.test.js
- test/integration.test.js
- test/plugins/normalize.test.js
- test/plugins/plugins.test.js
Fix #549
Currently users are forced to redefined all plugin in the pipeline to define a plugin options. That creates a lengthy option object and its error prone.
In addition several plugin uses the same options (i.e. `githubUrl`).
It's now possible to defined options directly under the `release` property, that will be passed to each plugins.
It's still possible to define options within the plugin definition to have it passed only to a specific plugin instance.
Adds the options `extends`, which can be defined via configuration file or CLI arguments to a single path or an array of paths of shareable configuration.
A shareable configuration is a file or a module that can be loaded with `require`.
Options is defined by merging in the following order of priority:
- CLI/API
- Configuration file …
> Shareable config

- .travis.yml
- README.md
- cli.js
- index.js
- lib/plugins/definitions.js
- package.json
- test/index.test.js
- test/integration.test.js
This PR remove the need for a CI `verifyConditions` plugin by:
- Moving the verification of the branch and PR in the core. Works with any major (and not so major) CI services. See [env-ci](https://github.com/pvdlg/env-ci) for the list.
- Leaving the responsibility to run `semantic-release` only on one job to the CI and/or the user.
**Benefits**
- Allow to support any CI out of the box
- Avoid forcing users who do not use Travis to override a big chunk of configuration (the `verifyConditions` plugins)
- Allow users to do a dry-run locally to verify the main and plugins configuration
- Allow to use shareable config more easily (Currently any shareable config user who do not use Travis would have to override the `verifyConditions` configuration defeating the purpose of shareable config)
- …
> Make semantic-release CI agnostic

- README.md
- cli.js
- index.js
- test/index.test.js
Doing releases outside a CI environment is not the recommended approach, but it might be useful in specific circumstances (for example #584 and [comment](https://github.com/semantic-release/semantic-release/pull/578#issuecomment-354579201)).
Since #578, `condition-travis` is not a default plugin anymore and verifying that `semantic-release` runs after all other CI jobs are successful is done externally, therefore allowing local releases is just a couple line change. So why not.
In addition the `Can I run this on my own machine rather than on a CI server?` FAQ mention it is possible even though it's not since several releases, so it was probably possible at some point. No real reason to remove (or more exactly continue to remove) a feature that was present before.
The FAQ clearly mention …
> feat: allow to release from local machine

- docs/support/FAQ.md
- index.js
- test/index.test.js
Exclude commits from the analysis if they contains `[skip release]` or `[release skip]` in the subject or the body.
Fix #41
> feat: allow to exclude commits from analysis

- .travis.yml
- docs/recipes/travis.md
Fix #609
When using Build Stages (doc to be written), should we recommend to use the `script` or the `deploy` stage?
`script` would work as long as we only run `semantic-release` in it, which should be the case for the `release` stage. On the other hand using the `deploy` step might make more sense.
If we go with `deploy` even for Build Stages we should change that in each semantic-release repo so the recommendation would match what we do in our repos.
> Travis: recommend to use the `deploy` step instead of `script`

- cli.js
- index.js
- test/index.test.js
- test/integration.test.js
The `noCi` is no properly set based on the `--no-ci` CLI arg and it is overwritten by the `noCi` option.
Fix #616
> fix: fix the `--no-ci` arg parsing

- cli.js
- index.js
- lib/plugins/pipeline.js
- package.json
- test/index.test.js
- test/plugins/pipeline.test.js
Currently if an error is returned by a plugin's `verifyConditions` or `verifyRelease`,  semantic-release log the error and exit.
So if there is multiple plugins configured for `verifyConditions` or `verifyRelease` and several of them returns an error (i.e. multiple plugins are misconfigured) only the first error will be logged. That create a situation of trial and error for the user (run => plugin 1 errors out => fix config => run plugins 2 errors out => etc...).
With this PR all the plugins for `verifyConditions` and `verifyRelease` are executed, and all the errors are logged. This should help users to configure semantic-release more easily. It will also be beneficial if we create a report/notification feature (like GitHub issue or Slack message )
The `publish` step still stop at the …
> feat: log all verification errors

- index.js
- lib/hide-sensitive.js
- package.json
- test/hide-sensitive.test.js
- test/index.test.js
- test/integration.test.js
As we use several sensitive information in environment variables, a plugin could by accident output in the logs the value of the tokens or credential.
For example in order to access the git repository we use an https URL like `https:<GH_TOKEN>@github.com/owner/repo.git`. If a Git command fails we don't log the error as it would contains the repo URL with the token.
This PR process each `stdin` and `stdout` text to hide any value that is set via an environment variable containing the keywords `token`, `password`, `credential`, `secret`, `private`. This way both the core and plugins can safely log anything without risking to expose sensitive informations in the CI logs. 
Ref semantic-release/git#21
> feat: hide sensitive info in stdout/sdtin

- lib/get-git-auth-url.js
Allow to defined a both `GIT_CREDENTIALS` for repository access and `GH_TOKEN` or `GL_TOKEN` for API access
> fix: prioritize `GIT_CREDENTIALS` for gtit credentials

- docs/recipes/gitlab-ci.md
- docs/recipes/travis.md
- docs/support/FAQ.md
- docs/support/node-version.md
- docs/usage/installation.md
Historically using an npm script to execute semantic-release has always been a stopgap solution for the rather ugly `semantic-release pre && npm publish && semantic-release post` hack.
Now that this script is no longer necessary (excellent work 👏) I felt like it would be desirable to get rid of the npm script in the first place. This becomes especially true with the differentiation between local and global installs, which was referenced throughout the docs, and makes it necessary to write every configuration guide (or at least parts of it) twice.
Luckily `npx` makes this extremely easy to do. `semantic-release` requires node version 8, which already ships with npx. (node@8.0.0 ships with npm@5.2.0 ships with npx@9.0.3).
`npx` will pickup the binary from the local `./node_modules/.bin` …
> Recommend to execute semantic-release via npx

- lib/get-git-auth-url.js
- test/get-config.test.js
- test/get-git-auth-url.test.js
Git url with format `git+https` are not supported when used in `git push <URL> ref`. It errors out with `fatal: Unable to find remote helper for 'git+https'`.
In some rare cases `get-git-auth-url.js` is producing a `git+https` URL.
It happens if:
- The repository is a GitHub `https` URL as `normalize-package-data` transforms it to a `git+https` URL
- No Git authentication is set (for example when the user uses ssh keys) as in that case `get-git-auth-url.js` returns the URL as is
> fix: always transform `git+https` URLs to `https`

- lib/get-config.js
Since #623, it's now safe to log more debug info. This way we log all options with `debug`, including the one specific to plugins. That would help troubleshooting.
> fix: debug log all options

- cli.js
- index.js
- package.json
- test/cli.test.js
- test/index.test.js
- test/integration.test.js
- Replace `commander.js` with `yargs`
- Add CLI unit tests
- Add a `--version` option
- Improve `--help` output
- Remove `commander.js` related workaround
- Allow to set list option with arg repetition or space separated list
- Maintain the list options defined as comma separated list
>  feat: improve CLI

- lib/get-config.js
- test/get-config.test.js
- test/helpers/mockserver.js
If `repositoryUrl` is set as a sematnic-release option (via `--repository-url` or `repositoryUrl` in `package.json`) the `GIT_CREDENTIALS` are not applied to the URL.
/cc @trollr
>  fix: set repository authentication when `repositoryUrl` is set as an option

- docs/usage/configuration.md
- lib/definitions/plugins.js
- test/index.test.js
Fix #664 
TODO:
No need to change the `peerDependencies` of any plugin.
> fix: remove the github plugin from default success and fail hooks

- docs/usage/configuration.md
- lib/definitions/plugins.js
BREAKING CHANGE: `success` and `fail` hooks are now enabled by default
In order to disable the `@semantic-release/github` plugin for the `success` and `fail` hook, the corresponding options have to be set to `false` in the **semantic-release** configuration:
```json
{
"release": {
"success": false,
"fail": false
}
}
```
Users who do not use the `@semantic-release/github` plugin, should disable it in the `success` and `fail` by setting the corresponding options to `false` or to alternative plugin providing `success` and `fail` hooks.
> feat: use `@semantic-release/github` as default for `success` and `fail` hooks

- lib/get-config.js
- test/get-config.test.js
- test/integration.test.js
Fix #667
Use the unmodified configured repositoryUrl (without adding the credentials) if it works, otherwise do as of now and convert the URL to `http`/`https` and add the credentials.
This allow users to push tags and commits via ssh while still using the GitHub/GitLab API.
> fix: do not transform repositoryUrl if it allow to push

- index.js
- lib/verify.js
- test/index.test.js
- test/verify.test.js
Verify the branch is the release branch before doing any other verification.
Otherwise the plugin and Git authentication are verified when building on other branches. If the branch is in a cloned repo (if building pushes from PR's) the environment variables will not be available and semantic-release will wrongly report the authentication error.
> fix: verify branch first

- lib/hide-sensitive.js
- test/hide-sensitive.test.js
> fix: exclude empty env var value from replacement

- README.md
- cli.js
- docs/extending/plugins-list.md
- docs/usage/configuration.md
- docs/usage/plugins.md
- index.js
- lib/definitions/plugins.js
- lib/git.js
- package.json
- test/cli.test.js
- test/definitions/plugins.test.js
- test/git.test.js
- test/index.test.js
- test/plugins/plugins.test.js
Proof of concept for #649.
Related to semantic-release/npm#52.
This PR introduce the `prepare` plugin hook, that will be called before create the Git Tag and the `publish` hook.
Currently plugin that create a file that can be committed (e.g. a `CHANGELOG.md`), create a commit or publish to a registry all operate in the `publish` hook. As some plugins require to have the Git tag created in the remote repo before publishing we currently have to create the tag before calling the `publish` plugins and update the tag whenever a plugin create a commit.
This is a quite inelegant solution...
That leads to creation/deletion/re-creation of Git tags for each plugin doing a commit as described in #649.
The addition of the `prepare` hook make things more organized and cleaner:
- `prepare` => Do all …
> feat: add the `prepare` plugin hook

- CONTRIBUTING.md
- README.md
- docs/usage/installation.md
- docs/usage/plugins.md
This PR is for issue #653 
Fixed some spelling and grammar mistakes for README.md, CONTRIBUTING.md, installation.md, and plugins.md
For plugins.md I modified the descriptions so that they didn't begin with "Plugin" e.g.
```
generateNotes plugin
Plugin responsible for generating release notes
```
changed to 
```
generateNotes plugin
Responsible for generating release notes
```
It seemed redundant to have "plugin" in the title and then begin the description with "plugin".
> docs: fix grammar and typos

- lib/get-last-release.js
- test/get-last-release.test.js
> fix: exclude prereleases from version retrived by `getLastRelease`

- docs/usage/configuration.md
`semantic-release` will not work. `semantic-release*` will work, too, and is better because it will also work for logs where we use just 'semantic-release' as scope. Let me know if you’d like me to change that
> Configuration: environment variable `DEBUG` must be set to `semantic-release:*`

- docs/usage/configuration.md
- lib/get-config.js
- lib/get-git-auth-url.js
- package.json
- test/get-config.test.js
- test/get-git-auth-url.test.js
Per discussion in #695.
- `owner/repo` => `https://github.com/owner/repo.git`
- `gitlab:owner/repo` => `https://gitlab.com/owner/repo.git`
- `bitbucket:owner/repo` => `https://bitbucket.com/owner/repo.git`
> feat: allow to use shorthand for `repositoryUrl`

- index.js
- lib/get-config.js
- lib/get-git-auth-url.js
- lib/git.js
- lib/verify.js
- test/get-config.test.js
- test/get-git-auth-url.test.js
Fix #707 
This also remove the `execa` timeout as it doesn't work with a prompt. I'll investigate more for an alternative solution to implement a timeout in such case.
> fix: prevent git prompt before permissions verification

- docs/usage/ci-configuration.md
- docs/usage/configuration.md
- docs/usage/shareable-configurations.md
This PR relates to issue #653 
Fix minor grammar and spelling errors in  ci-configuration.md, configuration.md, and shareable-configurations.md.
Fix default value in the documentation for dryRun option, dryRun is set to `true` when not running in CI environment
> docs: fix grammar and typos in CI configuration, configuration, and shareable configuration guides

- package.json
Explicitly upgrade to `git-url-parse` to 8.3.1 as 8.3.1 has a bug: https://github.com/IonicaBizau/git-url-parse/issues/65
Fix #727
> fix(package): update git-url-parse to version 8.3.1

- lib/get-last-release.js
- test/get-last-release.test.js
> fix: match tag to `tagFormat` from the begining of the string

- docs/extending/plugins-list.md
I made a set of plugins to help releasing chrome extensions to chrome webstore. It is available on [GitHub](https://github.com/GabrielDuarteM/semantic-release-chrome) and on [npm](https://www.npmjs.com/package/semantic-release-chrome) as well.
> Add semantic-release-chrome to the list of community plugins

- docs/support/troubleshooting.md
Adds clarifying information with regards to NPM error 403 as discussed in this issue: https://github.com/semantic-release/semantic-release/issues/747
> docs: add details on NPM error 403 to troubleshooting doc

- docs/usage/plugins.md
- docs/usage/shareable-configurations.md
> docs: add link to shareable configs and plugins list

- lib/git.js
Fix #786.
Seems to fix the issue according to https://github.com/semantic-release/semantic-release/issues/786#issuecomment-387830848
> fix: use `git rev-parse origin/${branch}` to verify origin head

- index.js
- lib/definitions/errors.js
Clarify that the error might be due to an invalid `repositoryUrl` configuration.
Fix #795
> fix: add clarification in EGITNOPERMISSION error message

- docs/extending/plugins-list.md
semantic-release-docker is compatible with latest semantic-release now,
see peerDependency: https://david-dm.org/felixfbecker/semantic-release-docker?type=peer
> docs(plugins): remove version warning about semantic-release-docker

- lib/plugins/normalize.js
- test/plugins/normalize.test.js
added quotes around plugin name to set it apart from the message. without the quotes, some consumers
were missunderstanding the successful loading of the `fail` plugin as a load failure and assuming
something was broken
resolves #811
> fix(plugin-load): clarify load message

- index.js
- lib/definitions/errors.js
- lib/git.js
- test/git.test.js
- test/helpers/git-utils.js
- test/index.test.js
- test/integration.test.js
Fix #793
This change use `git ls-remote` instead of `git rev-parse origin/branch` to obtain the head sha of the remote branch. This way it's the actual remote head that is retrieved instead of the one present in the local `.git/refs/heads/branch`.
The problem in #793 happens when a commit is pushed to the repo after the CI created the clone. In that situation the remote repo is ahead but the clone is not aware of that. Using `git ls-remote` solve this issue.
>  fix: use `git ls-remote` to verify if the remote branch is ahead

- lib/definitions/plugins.js
- test/definitions/plugins.test.js
This change allow to disable the `publish` hook (or to configure no plugins for that step).
The rational behind checking a plugin is set for the `publish` step was that there is no reason to run semantic-release at all if nothing get published.
However a lot of thing change since then and we now have the `prepare` step and the core is now creating the git tag.
So there might be situation where a user want to only create a tag, and maybe create a commit with the `@semantic-release/git` plugin during the `prepare` step. In such situation nothing should happen in the `publish` step (no npm release, no github release etc...), therefore it make senses to disable it.
> feat: allow to disable the publish plugin hook

- lib/git.js
Certain CI do not provide the tags, even after a `git fetch --unshallow --tags`.
Logging the error with `debug` would help troubleshooting such CIs environments.
> fix: add debug log for `git fetch` command

- index.js
- test/index.test.js
> fix: allow empty release notes in dry-run mode

- docs/support/FAQ.md
Fix #172.
Depends on https://github.com/semantic-release/commit-analyzer/pull/78 and https://github.com/semantic-release/release-notes-generator/pull/92.
> docs: FAQ for reverting a release

- index.js
- lib/git.js
- test/git.test.js
Fix #838
In case the authentication token provided is unauthorized the call to `isBranchUpToDate` will fail due to lack of read permission if that URL is used. As a result the error about outdated local branch will be reported instead of the one about missing permission.
By using the original (unauthenticated) URL `isBranchUpToDate` shouldn't fail due to permission as it requires only read permissions, that are necessarily present as the CI was able to clone the repo.
The issue #838 has been opened for several days now, I tested on my own and @wejendorp tested as well (see https://github.com/semantic-release/semantic-release/issues/838#issuecomment-401775032) so I think we can merge it.
> fix: use unauthenticated URL to check if branch is up to date

- docs/usage/configuration.md
- docs/usage/plugins.md
- index.js
- lib/definitions/constants.js
- lib/definitions/errors.js
- lib/definitions/plugins.js
- lib/get-config.js
- lib/get-git-auth-url.js
- lib/plugins/index.js
- lib/plugins/normalize.js
- lib/plugins/pipeline.js
- test/definitions/plugins.test.js
- test/index.test.js
- test/integration.test.js
- test/plugins/normalize.test.js
- test/plugins/pipeline.test.js
- test/plugins/plugins.test.js
Fix #844
This PR allow to configure multiple `generateNotes` plugins and include a lot of refactoring/fixes/optimization in the plugin management.
While working on the multiple `generateNotes` part I found many related small issues and opportunities to clarify and simplify the code regarding the plugin management, so I included them here.
That's quite a lot of code change, but each individual and independent change is done in it's own commit. So it's a good idea to review commits one by one rather than reviewing the entire PR at once.
>  feat: allow to define multiple `generateNotes` plugins

- test/helpers/npm-registry.js
- test/integration.test.js
`npm-docker-couchdb` has been unpublished from Docker Hub and doesn't seems to be maintained.
See https://github.com/npm/npm-docker-couchdb/issues/3
> test: use `semanticrelease/npm-registry-docker` Docker image for tests

- package.json
- test/index.test.js
- test/integration.test.js
This way plugins can pipe a stream to `stdout` and `stderr` in integration tests.
> test: use real writable stream

- docs/usage/configuration.md
> docs: `analyzeCommits` does not accept an `Array`

- docs/extending/plugins-list.md
I made plugin to support generating release notes for projects on [Gerrit](https://www.gerritcodereview.com) repositories.
> docs: add semantic-release-gerrit to plugins list

- README.md
I created a Waffle board for the semantic-release organization: https://waffle.io/semantic-release/semantic-release.
I've been using it for a couple month and really love it!
Adding the badge on the README would allow user to easily track progress:
- Features currently worked on (In Progress)
- Features that will be implemented at some point (Backlog)
- Blocked issues that require answers (Pending)
- New issues + Issues to fix + feature requests under consideration (Inbox)
> docs: add Waffle.io README badge

- docs/usage/configuration.md
Update docs to reflect correct spelling of `false` in `ci` section.
> docs: Correct spelling of false

- docs/extending/plugins-list.md
I created an [Expo](https://expo.io/) plugin for Semantic Release, see it [here](https://github.com/bycedric/semantic-release-expo). 😄
> docs: add semantic-release-expo to plugins list

- docs/usage/plugins.md
- lib/definitions/constants.js
- lib/definitions/errors.js
- lib/definitions/plugins.js
- lib/plugins/index.js
- lib/plugins/utils.js
- test/definitions/plugins.test.js
- test/plugins/plugins.test.js
- test/plugins/utils.test.js
Fix #982
- Simplify plugins configuration (all plugins can be multiple now, so no more exception)
- Simplify code
- Make plugins config/docs more consistent
> feat: support multiple plugins for the `analyzeCommits` step

- index.js
- lib/definitions/plugins.js
- lib/get-logger.js
- lib/plugins/normalize.js
- test/index.test.js
- test/plugins/normalize.test.js
- test/plugins/plugins.test.js
This should avoid confusion when trying out semantic-release in dry-run mode regarding why `prepare`, `publish`, `success` and `fail` plugins are not executed.
> feat: add logs about `prepare`, `publish`, `success` and `fail` plugins skipped in dry-run mode

- docs/support/resources.md
- Add a missing quote mark
- Use straight quotes consistently
I suppose this falls within the scope of #653 :)
> docs/resources: fix quote marks

- lib/get-config.js
- test/get-config.test.js
This bug affects only plugins defined with the `plugins` option and wrapped in an Array to add a configuration
Fix #999
> fix: correctly resolve plugins installed globally with `npx`

- lib/definitions/plugins.js
- test/definitions/plugins.test.js
- test/index.test.js
Ref https://github.com/semantic-release/github/issues/138
> feat: allow `publish` plugins to return `false` in order to signify no release was done

- lib/get-last-release.js
- test/get-last-release.test.js
> fix: ignore lasst release only if pre-release on the same channel as current branch

- docs/extending/plugins-list.md
Adds a reference to the semantic-release-ado plugin on docs/extending/plugins-list.md.
> Add reference to semantic-release-ado plugin

- docs/developer-guide/js-api.md
There is an error in the JavaScript API documentation page. Copy/pasting the snippet as this makes the script fail with : 
```
The automated release failed with ReferenceError: pluginName is not defined
```
> Doc : correct way to print release plugin name

- README.md
The current commitlint URL goes to a repo which contains a redirect message and new URL.
Replace the outdated URL with the new URL for the commitlint repo.
> docs: update commitlint URL

- docs/extending/plugins-list.md
We created a new plugin for publishing messages from semantic release to a slack channel. The user can install a slack app and be notified depending on failure or success when running semantic release.
> docs: Added a new community plugin

- docs/extending/plugins-list.md
Adds the [sementic-release-circleci-orb](https://github.com/matt-oakes/semantic-release-circleci-orb) plugin to the 3rd party list.
> Add semantic-release-circleci-orb to the plugin list

- docs/usage/configuration.md
- lib/definitions/errors.js
We're migrating some old repositories that had been using a `develop` branch, and `semantic-release@beta` failed out of the box because we didn't have a `master` branch.
This PR adds a bit more detail to the error message and documentation to help the next person in my shoes.
> Docs/Improve `ERELEASEBRANCHES` error flow

- lib/get-git-auth-url.js
- test/get-git-auth-url.test.js
closes #1194
I’ll test this first with https://github.com/gr2m/github-npm-registry-test
> Prefix git auth with "x-access-token:" when run in a GitHub Action

- docs/usage/plugins.md
This patch documents that the `plugin` config option is an override, not a merge with the default. This is significant, for example, if you customise the github plugin as it will then prevent npm publishing by default unless the npm plugin is also defined manually.
> chore: document that plugins config is an override

- README.md
Since the readme hints at doing this, note that features to automate this are in beta. Also discussed at https://spectrum.chat/semantic-release/general/im-trying-to-configure-a-next-release~5bb8e692-a0cd-49be-8379-9fb6b25261fe
> docs: note publishing on distribution channels in beta

- .gitignore
- README.md
- SUMMARY.md
- docs/recipes/README.md
- docs/recipes/ci-configurations.md
- docs/recipes/git-hosted-services.md
- docs/recipes/package-managers-and-languages.md
- docs/support/FAQ.md
- docs/support/node-version.md
- docs/usage/ci-configuration.md
Includes:
- docs(recipes): cleaned doc and navigation
- Corrected inconsistancies between the sidebar and the actual pages. Remove non existing pages. 
- Clarified status of "Package managers and languages" to "to be completed".
- docs: repared broken links to "CI configuration recipes"
- docs: cleaned "Developer guide" section navigation
- docs: synched README.md and SUMMARY.md
Also added my (Jetbrains) IDE files to `.gitignore`.
> Doc cleanup

- package.json
Recently, the lodash package had a couple of patch version updates due to reported security vulnerabilites. This PR updates lodash to the last version. I reckon that similar updates are in order in the various other repositories related to semantic-release.
That said, it would be helpful to be able to run `npm audit` against this repository. Alas, that’s not possible because it has no package-lock.json.
> Update dependency lodash (patch version)

- package.json
Less dependencies to maintain.
Users who want to use Commitizen can use their own local install.
> chore: remove commitizen from our dependencies

- docs/03-recipes/travis.md
Fixed the link for `setup with semantic-release-cli.` in 'Environment Variables' section, refering a old file of this repo,
> docs: broken link docs/03-recipes/travis.md

- README.md
The goal here is to give a few example of the most popular tools (with a lot of GitHub stars) not to be exhaustive nor to endorse any tool, nor being used to promote a tool.
Fix #1184
> docs: limit list of suggested tools for commit linting

- docs/support/FAQ.md
- remove unnecessarily apostrophe in FAQ "how to revert section"
- improve punctuation of the how-to revert a release section
> docs: remove unnecessary apostrophe

- docs/recipes/README.md
- docs/recipes/github-actions.md
- docs/usage/ci-configuration.md
related https://github.com/semantic-release/semantic-release/issues/974
Just add a simple [GitHub Actions](https://github.com/features/actions) recipe.
> Add GitHub actions to recipes

- CONTRIBUTING.md
The lint fix command did not work because it was missing the extra `--`.
> docs(contributing): correct lint fix command

- README.md
- bin/semantic-release.js
- docs/support/FAQ.md
- index.js
- lib/branches/get-tags.js
- lib/git.js
- test/branches/get-tags.test.js
- test/git.test.js
- test/helpers/git-utils.js
Fix #1345
Required for semantic-release/git#155
> perf: use `git tag --merge <branch>` to filter tags present in a branch history

- index.js
- lib/branches/get-tags.js
- lib/get-last-release.js
- lib/get-releases-to-add.js
- lib/git.js
- test/branches/get-tags.test.js
- test/get-last-release.test.js
- test/get-releases-to-add.test.js
- test/git.test.js
- test/index.test.js
> fix: call `getTagHead` only when necessary

- docs/extending/plugins-list.md
I was recently looking for a plugin for [leiningen](https://leiningen.org/) projects.
I couldn't find one so I've put one together at https://github.com/NoxHarmonium/leiningen-semantic-release
It's fully tested using the https://github.com/NoxHarmonium/leiningen-semantic-release-test-clojars sample project.
I thought adding it to the community plugins list might save people some time!
Let me know if there is anything else I need to do, or any suggestions for improvements to the plugin that need to be done to get added here.
Thanks!
> docs: add leiningen-semantic-release to list

- package.json
Can't use `^7.0.0-beta.6` as it will still resolve to `7.0.0-beta-.2` which is the problem release.
More conversation about that here: https://github.com/semantic-release/semantic-release/pull/1361
> fix: update commit-analyzer dep version off errant publish

- .github/airtable-crm.yml
I don't think we use that any more
> build: remove `.github/airtable-crm.yml`

- index.js
- lib/branches/get-tags.js
- lib/branches/index.js
- lib/definitions/constants.js
- lib/get-release-to-add.js
- lib/git.js
- lib/utils.js
- test/branches/get-tags.test.js
- test/get-last-release.test.js
- test/get-release-to-add.test.js
- test/git.test.js
- test/helpers/git-utils.js
- test/index.test.js
- test/integration.test.js
- test/utils.test.js
this feature change the way semantic-release keep track of the channels on which a version has been released.
It now use a JSON object stored in a [Git note](https://git-scm.com/docs/git-notes) instead of Git tags formatted as v{version}@{channel}.
The tags formatted as v{version}@{channel} will now be ignored. If you have made releases with v16.0.0 on branches other than the default one you will have to update your repository.
The changes to make consist in:
- Finding all the versions that have been released on a branch other than the default one by searching for all tags formatted v{version}@{channel}
- For each of those version:
- Create a tag without the `{@channel}` if none doesn't already exists
- Add a Git note to the tag without the `{@channel}` containing the channels on which …
> feat: use Git notes to store the channels on which a version has been released

- docs/extending/plugins-list.md
Our company built an in-house extension and wanted to be able to release it to Chrome and Firefox both for distribution. The Chrome plugin worked without any issues, but we could not get the Firefox plugin to work. The package hasn't had a release for almost a year and half, and we think the Mozilla Add On store API changed since their last release. 
We built our own version using a different method to communicate with the Add On store that we've been using for almost 6 months now without any issues. We decided to open source the package, and will be maintaining it for the future. You can find our package [here](https://github.com/tophat/semantic-release-firefox-add-on).
We have detailed documentation about how to configure the plugin and unit testing. We're not on version 1.0 yet but …
> Replacing firefox plugin in the community list

- lib/git.js
> fix: use `--no-verify` when testing the Git permissions

- lib/git.js
- test/git.test.js
- test/helpers/git-utils.js
This PR adds `try-catch` block to `git.js`'s `getBranches` function. When you run the script without having any branches on remote origin (an empty repo) it throws an unclear error
```
An error occurred while running semantic-release: TypeError: Cannot read property '1' of null`
```
This PR fixes it so now the message looks like this:
```
ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration.
This may occur if your repository does not have a release branch, such as master.
Your configuration for the problematic branches is [].
AggregateError:
SemanticReleaseError: The release branches are invalid in the `branches` configuration.
```
> Filter out empty branch results

- docs/extending/plugins-list.md
I've written an integration for Gitea releases ~~and a plugin which enables back-merging a release into a develop branch (Git Flow)~~.
> docs: Add Gitea integration to plugins list

- docs/support/troubleshooting.md
> docs(Troubleshooting): release not found in prereleases branch (e.g. `beta`) after rebase on `master`)

- index.js
Fix #1454
the first call to `verifyAuth` would always fails because `branch` was `undefined`. As a result we wouldn't use the ssh URL in case we have ssh keys auth.
> fix: pass a branch name to `getGitAuthUrl`

- index.js
> fix: add `repositoryUrl` in logs

- docs/recipes/github-actions.md
These options work the same as the curl command, but use a GitHub App so there's no need to provision and manage a Personal Access Token in order to trigger the Semantic Release action.
Full disclosure, I'm personally involved with Actions Panel. Not involved at all with Action Button.
> Add alternative trigger options

- docs/usage/workflow-configuration.md
Thank you very much to the team working on semantic release! 
While taking a look at some of the workflow configurations, I noticed a few small typos and thought I would adjust them. Cheers! 🍺
> docs: adjust minor typos in workflow configuration

- lib/hide-sensitive.js
- test/hide-sensitive.test.js
> fix: prevent false positive secret replacement

- .gitattributes
As per https://github.com/semantic-release/semantic-release/pull/1574#issuecomment-643794681 this PR fixes what I experienced as unexpected and somewhat cryptic lint/test problems when checking out the repository on Windows while not specifying additional options or configured globally.
The fix is taken [right from the Prettier docs](https://prettier.io/docs/en/options.html#end-of-line). Makes sure text file line endings on Windows are `lf` instead of `crlf`, which typically has no adverse effects there when using a somewhat recent code editor.
The alternative would be to configure Prettier so it allows crlf line endings, but that would be a considerably larger diff, also because files in `bin/` would need to be excluded so these don't end up with crlf on npm, which would break the …
> build(gitattributes): eol=lf for Windows users

- docs/usage/ci-configuration.md
- lib/get-git-auth-url.js
- test/get-git-auth-url.test.js
Bitbucket Servers currently only support basic auth, so it is not possible to authenticate with `x-auth-token:{token}`, you need to put your username before the token or use bearer headers.
> feat(bitbucket-basic-auth): support for bitbucket server basic auth

- docs/usage/configuration.md
Thanks again for the awesome project!!!
github documentation has moved to `docs.github.com`
addressing this change
> docs: update github documentation to `docs.github.com`

- docs/support/FAQ.md
As discovered (the hard way) https://github.com/semantic-release/semantic-release/issues/1593 the package semantic-release *does not* update the `package.json` its the module `semantic-release/npm` that does. This improves the documentation to avoid any ambiguity. 
fixes #1593
> docs: be clear about what module of semantic-release handles updating  the package.json

- docs/usage/configuration.md
Earlier there were some discrepancies in the doc https://semantic-release.gitbook.io/semantic-release/usage/configuration for the **dry run** feature (_eg. the description of the steps skipped in the process were not apt_). Hence, this PR to update the documentation for dry-run with details and missing info to get a clear picture of what the --dry-run flag actually does.
Fixes #1533
> docs(configuration.md): Updated documentation for dry-run feature of semantic Release

- lib/get-git-auth-url.js
When setting up semantic release in CI, the debug logging does not provide enough context on why it is trying to push via https, and is hard to debug without deeply reading the code.  Adding some debug logging to indicate that will make it easier to know why you're calling git via https.
> fix: Add logging for when ssh falls back to http

- CONTRIBUTING.md
It had the backticks (`) around the messages, but I think they were unintentional, probably a leftover from copy-pasting.
> docs(CONTRIBUTING): fix commit message examples

- docs/usage/plugins.md
**Summary**
Reorder the list of default plugins in the documentation from alphabetical to execution order. 
**Motivation**
The documentation clearly states the four default plugins that are already installed with semantic-release. However their default order of execution is not explicitly stated and when listed in alphabetical order implies the incorrect order.
When a package maintainer needs to configure options on one or more default plugins the documentation states that the `plugins` property will be overridden instead of merged.
> Note: If the plugins option is defined, it overrides the default plugin list, rather than merging with it.
For that reason the maintainer must add all default plugins to the configuration list to modify the configuration of a single plugin. When looking at …
> docs: reorder default plugins list

- CONTRIBUTING.md
- lib/definitions/errors.js
- lib/get-config.js
- package.json
- test/get-config.test.js
addresses bad DX reported in #1655 /cc @kentcdodds @travi
> feat: Throw an Error if package.json has duplicate "repository" key

- docs/extending/plugins-list.md
Adds a new plugin in the list of additional plugins for `semantic-release`.
This plugin allows to automatically deprecate old versions as part of the release process.
> docs: add npm-deprecate-old-versions in plugins list

- lib/get-git-auth-url.js
- test/get-git-auth-url.test.js
See #1670 for details about the issue. Here is a regular expression proposal that supports port parsing :
```
^(?!.+:\/\/)(?:(?<auth>.*)@)?(?<host>.*?):(?<port>\d+)?:?\/?(?<path>.*)$
```
It is parsing as expected the following example URLs :
```
localhost:2080/git/test.git
localhost.null:2080/git/test.git
localhost.null:git/test.git
localhost.null:/git/test.git
localhost:2080/group/git/test.git
localhost.null:2080/group/git/test.git
localhost.null:group/git/test.git
localhost.null:/group/git/test.git
git@localhost:2080/git/test.git
git@localhost.null:2080/git/test.git
git@localhost.null:git/test.git
git@localhost.null:/git/test.git
git:pass@localhost:2080/git/test.git
git:pass@localhost.null:2080/git/test.git
git:pass@localhost.null:git/test.git
git:pass@localhost.null:/git/test.git
```
> Don't parse port as part of the path in repository URLs

- lib/get-git-auth-url.js
- test/integration.test.js
See #1668 for details about the issue. Here I will discuss about the fix implementation.
If the given URL works out of the box or if a single token is available in the environment, the behaviour remains unchanged.
However if there is multiple tokens available, it will perform a `git.verifyAuth` call for each of them, and return the first of them that is working.
If none of them are working, it will return the URL as is.
This behaviour is tested in `integration.test.js`. It isn't tested in `get-git-auth-url.test.js` because I need gitbox functionalities to test it.
> Use valid git credentials when multiple are provided

- lib/hide-sensitive.js
- test/hide-sensitive.test.js
> fix: escape uri encoded symbols

- docs/extending/plugins-list.md
This adds a semantic-release-plugin which we use to update our license files (copyright dates and more) based on their type.
> docs: add semantic-release-license-plugin

- package.json
This new version includes a fix for a ReDoS vulnerability in `semver-regex` that is flagged by some source composition analysis tools like Snyk:
https://snyk.io/vuln/SNYK-JS-SEMVERREGEX-1047770
It's a major version because it drops support for Node.js 6.x. This doesn't affect us since we already require Node.js >=10.18.
https://github.com/sindresorhus/find-versions/releases/tag/v4.0.0
> fix(deps): Require find-versions ^4.0.0

- docs/usage/plugins.md
Document the `addChannel` step defined in https://github.com/semantic-release/semantic-release/blob/e35e5bb73f3628906553709ac0f5beb8f565c61a/lib/definitions/plugins.js#L83-L84
This step is used in [@semantic-release/npm](https://github.com/semantic-release/npm).
> docs(plugins): document `addChannel` step

- lib/get-config.js
- test/get-config.test.js
This makes sure that `options.ci` is respected even when set inside a shareable config.
Closes #1728.
> Normalize `ci: false` into `noCi: true` after configs get merged

- docs/support/FAQ.md
> If you wish to only update the `package.json` and push via Git you can set the project to `"private": true,` within your `package.json` to prevent publishing to [npm](https://www.npmjs.com). This can be useful for using **semantic-release** with a non-node project.
This is still describing a node-project.
> docs: clarify node vs npm in FAQ

- bin/semantic-release.js
Log errors in the main binary to the console to help with debugging.
I wasn't sure how to add tests for this, as I couldn't find any existing tests for that file.
closes #1734
> fix: add logging for top-level errors

- package.json
fixes vulnerability in y18n which is a dependency of yargs version 15:
https://nvd.nist.gov/vuln/detail/CVE-2020-7774
> fix(deps): update to yargs 16.2.0

- test/helpers/git-utils.js
> Do not throw error when unshallow a complete repository
will fail if one uses a new enough git and has set `init.defaultBranch` (mine is set to `main`).
> fix: pin initial branch to master

- .github/workflows/test.yml
- .npmrc
to avoid updating to a dependency version that does not support our supported range
i know we've been attempting to avoid config files in the root of the projects where possible, but i'm not sure if there is a good way to accomplish this same goal in another way. i'm open to thoughts around whether we are ok proceeding in this way or if we should consider an alternative.
> build(engine-strict): strictly enforced node version compatibility for dependencies

- README.md
> docs(README): change link to Angular's Contribution guidelines instead of Angular.js's Developers guide

- lib/get-config.js
- test/get-config.test.js
This change adds support for `*.cjs` config files by removing the explicit use of `searchPlaces` options and relying and the default search places generated by `cosmicconfig`.  As per the docs for [`cosmicconfig`][cc], the defaults include all the extensions/formats previously supported by semantic-release in addition to the new .cjs variants.
Resolves [#1814][issue].
[issue]: https://github.com/semantic-release/semantic-release/issues/1814
[cc]: https://github.com/davidtheclark/cosmiconfig#searchplaces
> feat(config): Use cosmiconfig defaults to support .cjs config files

- docs/developer-guide/plugin.md
As I was reading the documentation and starting my own plugin project, I noticed while trying to print the context object content in different situations, that the documentation has some errors:
- analyzeCommits missing from the lifecycle list
- "verify" lifecycle should be "verifyConditions"
These are addressed by this pull request.
> Minor fixes to documentation

- package.json
See CVE-2021-23337
fixes #1930 thanks @gnanderson
> fix: bump minimal version of lodash to address `CVE-2021-23337`

- docs/usage/workflow-configuration.md
Just a small typo fix where incorrect usage of "there" was found.
Thanks for building and maintaining such a great tool!
> docs(workflow-configurator): fix single typo

- docs/developer-guide/plugin.md
A correction to the earlier documentation: the "nextRelease" object is NOT similar to the
lastRelease and there are some differences. Because of this, the object is now documented as a
separate entry. Added also information on how the error handling should be done so that
semantic-release would be able to handle errors from plugins properly and call "fail" lifecycle
plugins. Included some more advanced information on how the analyzeCommits-lifecycle plugins work
and how the result of the initial analyzer can be overridden. This is an edge case, but could happen
and is good to understand.
> docs(plugin developer guide): correction, additional details / advanced

- docs/extending/plugins-list.md
@semantic-release-plus/docker is a fork of semantic-release-docker converted to typescript and 100% test coverage added.
@semantic-release-plus/docker also adds the functionality to support major, minor tagging.
(cherry picked from commit f30981403320bc8bec351498ed3e4f27ea754362)
> docs: adds docker community plugin that supports major, minor tagging

- docs/usage/plugins.md
See this discussion: https://github.com/semantic-release/semantic-release/discussions/1987#discussioncomment-917795
I'm new to semantic-release and was originally confused by the order, so hopefully this clears it up a little for newcomers.
cc @travi
> docs(plugins): clarify order of execution

- docs/recipes/circleci-workflows.md
Updates the included CircleCI config file example.
* Now uses 2.1 style config
* Uses Node Orb
* Use pre-defined node/test job
* Uses Matrix jobs to test multiple node versions.
* Updated Node versions
* Using new CircleCI docker images (from node executor)
* Updated language/terminology in description
> docs(circleci): Update CircleCI recipes config

- .github/workflows/test.yml
- package-lock.json
- package.json
since marked v3 requires node v12
> fix(marked): reverted upgrade to v3

- docs/recipes/github-actions.md
The link to the secrets and environment variables was broken since the documentation changed.
I pointed the link to the URL that made most sense, since users can choose to create the secret wherever they want.
> docs: fix broken link on github actions recipe

- docs/developer-guide/plugin.md
Based upon my research in https://github.com/semantic-release/semantic-release/discussions/2137.
> docs: add section on logger usage for plugins

- docs/extending/plugins-list.md
The plugin will send information about the new release to a mattermost webhook.
> docs: add semantic-release-mattermost to the plugin list

- docs/extending/plugins-list.md
This plugin allows automatically marking NPM releases as deprecated.
```yml
[
"semantic-release-npm-deprecate",
{
"deprecations": [
{
"version": "< ${nextRelease.version.split('.')[0]}",
"message": "Please use ^${nextRelease.version.split('.')[0]}.0.0."
}
]
}
]
```
> docs: add semantic-release-npm-deprecate plugin

- README.md
shields.io now has our official logo available through `simple-icons`. 
i was trying to get just the logo on the dark part of the left, similar to the previous version, but was unsuccessful without text content on both sections. i dont hate having `semantic` on the left section and `release` on the right section, but removing the `-` steps away from the official name. i'm interested in thoughts around how this is actually rendering.
also, i'm not sure what the history is around the color used for the badge. is it still the most appropriate for the project? i have no reason to change it, but thought this was a good chance to at least confirm.
> docs(badge): switched to proper semantic-release logo

- package-lock.json
- package.json
This PR fixes CVE-2021-23425 which was just fixed in the downstream project https://github.com/semantic-release/commit-analyzer/pull/289.
@travi could you please review this PR as well?
> fix: bump @semantic-release/commit-analyzer to 9.0.2

- README.md
From https://github.com/semantic-release/semantic-release/issues/1825#issuecomment-978119923:
> @chalkygames123 are you interested in opening a PR that updates the readme badge and the docs suggesting the badge to use in projects using semantic-release?
@travi Well, about the latter, honestly, I found it kind of hard to write because English is not my first language 😅 So for the sake of accuracy, would you mind if I leave it to you?
> docs: update badges to include preset names

- README.md
since this is a common confusion point for new folks
> docs(breaking-change): highlighted the need for `BREAKING CHANGE: ` to be in the commit footer

- docs/usage/workflow-configuration.md
The documentation says:
> If the `prerelease` property is set to `true` the `name` value will be used.
But then the example referring to this behaviour has the the `prerelease` value set to `'beta'` instead of `true`.
> docs: wrong prerelease example

- docs/usage/ci-configuration.md
This PR updates the broken link to CI configuration recipes which was caused by a directory structure change I guess.
> docs: update broken link to CI config recipes

- index.js
- test/index.test.js
> fix(log-repo): use the original form of the repo url to remove the need to mask credentials

- docs/usage/configuration.md
After a lot of suffering trying to debug some issues with semantic-release, I finally noticed `addChannel` is also skipped on dryRun mode, but it isn't documented 
https://github.com/semantic-release/semantic-release/blob/master/lib/definitions/plugins.js#L85
> docs(configuration.md): `addChannel` step is skipped when `dryRun` is enabled

- docs/support/node-version.md
- Drop duplicate word `requires`
Drive-by PR, not closing any issue with this.
> docs: drop duplicate word

- docs/recipes/release-workflow/distribution-channels.md
- Fix typo in word `feedbacks`, feedback is always singular
Drive by PR, not closing any issue with this PR.
> docs: fix typo

- docs/developer-guide/plugin.md
- docs/extending/plugins-list.md
- docs/extending/shareable-configurations-list.md
- docs/recipes/ci-configurations/gitlab-ci.md
- docs/support/FAQ.md
- docs/usage/configuration.md
- Fix typos
- Use `monospace` style for some terms
- Fix whitespace
Drive by PR, not closing any issue with this.
> docs: fix typos

- docs/recipes/ci-configurations/gitlab-ci.md
The usage of only/except in Gitlab pipelines is not recommended to use for newer pipelines according to this documentation: https://docs.gitlab.com/ee/ci/yaml/#only--except
We should update the documentation accordingly.
> docs: remove deprecated keyword in gitlab-ci.md

- docs/extending/plugins-list.md
The [semantic-release-space](https://github.com/123FLO321/semantic-release-space) plugin allows creating JetBrains Space Deployments with semantic-release.
> docs(plugin-list): add semantic-release-space plugin

- test/helpers/gitbox.js
- test/helpers/mockserver.js
while the gitbox image now appears to be working properly, the mockserver image is still having
problems, so this does not fully get the tests working on arm yet
for #2478
> test(integration): upgrade the gitbox image to support arm architecture in addition to x86

- package-lock.json
- package.json
- test/branches/branches.test.js
- test/cli.test.js
- test/get-config.test.js
- test/index.test.js
- test/integration.test.js
for #2133
this takes care of one of the tasks needed for the ESM conversion, as mentioned in https://github.com/semantic-release/semantic-release/issues/2133#issuecomment-1196971437
i think we should also replace use of sinon with testdouble, but i'd rather do that as a separate step. that change is not required for the ESM conversion, like this change is, but would remove the complexity of using multiple stubbing libraries.
> test: replaced proxyquire with testdouble

- docs/support/troubleshooting.md
**Current behaviour:**
Troubleshooting.md states to delete git remote tag: 
> You can delete each tag from remote using `git push origin :[TAG NAME]`, e.g. `git push origin :v2.0.0-beta.1`
This results to failing since tag already exist
**Expected:**
`-d` flag should be included
> You can delete each tag from remote using `git push origin -d :[TAG NAME]`, e.g. `git push origin -d :v2.0.0-beta.1`
> docs: fix troubleshooting git delete remote tag command

- docs/extending/plugins-list.md
Add a new community plugin that I created to publish `crates.io` cargo packages (Rust language)
> docs(plugins list): add semantic release cargo community plugin

- index.js
- package-lock.json
- package.json
- test/index.test.js
- test/integration.test.js
> forced plugins to use beta version of semantic-release

- docs/usage/plugins.md
Fixes a typo with `analyzeCommits`
> docs(plugins): fix typo

- test/fixtures/plugin-noop.cjs
- test/index.test.js
based on https://github.com/semantic-release/semantic-release/blob/78ea3ba966c973ccc283b88cf490bd7ddee088c7/lib/plugins/normalize.js#L17, i think this test was wrong before and this change fixes it. i think i read the logic correctly, but the fact that this test has been the other way for a long time makes my confidence low that this is the right change, so i could really use a sanity check on this one.
for #2543
> test: aligned pluginName with naming for functions

- bin/semantic-release.js
- index.js
- lib/plugins/pipeline.js
> fix(secrets-masking): used the proper named import from hook-std to enable masking for stderr

- .github/workflows/test.yml
- package-lock.json
- package.json
in accordance with our node support policy:
https://semantic-release.gitbook.io/semantic-release/support/node-support-policy
BREAKING CHANGE: Node v18 or greater is now required. Please refer to
https://semantic-release.gitbook.io/semantic-release/support/node-version for recommended options
for releasing with a supported node version.
for #2543
> feat(node-versions): raised the minimum required node version to v18

- docs/recipes/ci-configurations/github-actions.md
v2 uses a very old version of Node and produces a deprecation warning. we should use v3.
> docs: update GH Actions recipe actions to v3

- docs/support/node-version.md
The [lts tag](https://www.npmjs.com/package/node?activeTab=versions) refers to Node.js 16.13.2. To use v18 of Node you need to use the tag `v18-lts`.
> docs: update node LTS version for npx command

- docs/recipes/release-workflow/pre-releases.md
There is a tiny typo in the version mentioned in `Working on another future release` section. It says that installing with `npm install example-module` will still receive version `1.0.0`, but in fact, there was a bug fix made on the default distribution channel one step before.
> docs(pre-releases): Correct @latest version in semantic-release

- package-lock.json
- package.json
Reverts semantic-release/semantic-release#2676 
i think this is related to the tests not exiting correctly
> Revert "chore(deps): update dependency ava to v5.1.1"

- bin/semantic-release.js
- lib/plugins/utils.js
Updates to support running on Windows post the esm conversion.
1. [fix: Detect git version on windows](https://github.com/semantic-release/semantic-release/commit/301687fc0cb9e8caf0999b3926132168826d47be) 
git does not fully match semver, especially on the windows version. Using loose checking in findVersions is able to match the version.
2. [fix: use file:// url loading plugins](https://github.com/semantic-release/semantic-release/commit/3ec47a33fe98c857d773865187253ebadf766875)
The `file://` url is required for the `win32`platform but supported on all platforms.
> fix(windows): fixed issues preventing execution from windows

- lib/plugins/utils.js
- test/fixtures/plugin-esm-named-exports.js
- test/integration.test.js
- test/plugins/utils.test.js
this cherry-picks commits that originally landed in the current beta branch in order to backport the esm plugin loading capability into the mainline ahead of the beta branch landing.
> feat(plugins): add support for loading ESM plugins

- test/integration.test.js
Two tests had the same package name, causing random concurrency failures during CI testing.
An example of the conflict is in [this](https://github.com/semantic-release/semantic-release/actions/runs/4191434175/jobs/7265855238) CI run.
> test(integration): fix package name conflict

- .github/workflows/test.yml
Issues are preventing ci jobs from completing.  This patch reduces the timeout from the default timeout of six hours.  The logs are not always viewable until the timeout so this should help in problem examination.
> ci: set test workflow timeout to 10 minutes

- test/helpers/gitbox.js
- test/helpers/mockserver.js
- test/helpers/npm-registry.js
There is legacy support for PortBindings and Binds at the root level of the config.  Currently (including Windows) these reside under the HostConfig.  ExposedPorts is now used to identify the externally available ports.
Tests run when sideloaded for Linux testing [here](https://github.com/webstech/testteeny/actions/runs/4290352828/jobs/7474281208).  On Windows, it runs locally  but fails on GitHub server with a `docker image not found` error (not related to config change).  Researching the Windows error.
> test: update docker config for windows support (#2721

- test/integration.test.js
A pair of patches to the integration tests. 
1. ci: win32 escape slash as doubleslash for test
Pathing in stderr output has double backslash in the filename.  The test will now use double backslash in the existence test.
2. ci: avoid Windows pop-up in credential tests
Windows uses a `credential.helper` that will open a pop-up for credentials if they are missing.  A git config parameter will now be set in the environment to avoid the pop-up.
> test: Windows support in integration tests

- README.md
npm package provenance is a big thing for open-source supply chain security and should receive increased awareness and promotion to help secure the ecosystem of 3rd-party packages.
The npm package provenance setup exists in the [semantic-release/npm package readme](https://github.com/semantic-release/npm#npm-provenance) but it's easily missed out on when someone searches the main project's README.
This PR updates the list of supported features to make the feature easily accessible and promote it for users.
> docs: Update README.md with npm package provenance

- docs/developer-guide/js-api.md
- docs/usage/installation.md
confirmed in https://github.com/travi-test/semantic-release-tester/commit/0c14764598290d9869fa1a0f6e4d3b1885d23ee5
> docs(npx-version): mentioned using a renovate regex manager to update the version

- .github/workflows/release.yml
the goal with this is to make releases more deterministic based on commit rather than a point in time. in combination with https://github.com/semantic-release/.github/pull/18, we should continue to release with the latest version, but without that dependence on time.
> ci(release): pinned the version of semantic-release

- test/helpers/gitbox.js
- test/helpers/mockserver.js
- test/helpers/npm-registry.js
- test/integration.test.js
this uses the technique for waiting for the pull to complete [from the dockerode readme](https://github.com/apocas/dockerode/tree/edf29ccb2c2c7bfcdd1cf3cacbe861bd0f4bc87a#helper-functions) and mostly gets rid of our dependence on get-stream.
the [remaining get-stream usage](https://github.com/semantic-release/semantic-release/blob/45eb11ae9cb46e6167ecfa255ae5c62ab0d016ff/lib/git.js#L49) is the `.array()` that is [removed in v7](https://github.com/sindresorhus/get-stream/releases/tag/v7.0.0). i suggest we deal with that usage separately from this PR
> test(integration): properly waited for the image pulls to complete

- .github/workflows/scorecard.yml
- README.md
the changes to detect semantic-release in github actions workflows was [released yesterday](https://github.com/ossf/scorecard/releases/tag/v4.11.0), so it feels like the right time to add this to our workflows. 
our [current score is 7.7](https://securityscorecards.dev/viewer/?uri=github.com/semantic-release/semantic-release), but i expect that to go up once this is merged and the score is recalculated with the new detection for semantic-release. i'm hopeful that the failure to detect our license might also be fixed, but i haven't dug in to confirm that one 🤞🏼
> ci(ossf-scorecard): added workflow calculating scorecard metrics

- docs/extending/plugins-list.md
https://www.npmjs.com/package/@google/semantic-release-replace-plugin now points to `semantic-release-replace-plugin`.
> docs(plugins): change to new repo and package name

- docs/recipes/ci-configurations/gitlab-ci.md
~~probably best to wait for https://github.com/npm/documentation/pull/686 to merge first~~ merged
> docs(gitlab): highlighted that GitLab CI is now a supported CI provider for provenance

- docs/extending/plugins-list.md
The name of the plugin already exists so I added `(alternative version)` as I did not want to write `@terrestris/maven-semantic-release`.
> add @terrestris/maven-semantic-release plugin

- package-lock.json
- package.json
> fix(deps): upgraded `release-notes-generator` and `commit-analyzer` plugins to stable versions

- package.json
closes #2968
since this was added as a cleanup item to a major release that was primarily intended to unblock folks seeing incompatibilities with the latest conventional-changelog presets, we didnt intend for this to break potentially legitimate extension of semantic-release in the process. 
we want to use what we learned from this to more intentionally define this programatic API in a future breaking release through https://github.com/semantic-release/semantic-release/issues/2978 instead.
> fix(exports): removed the `exports` definition for the time being

- docs/support/FAQ.md
Fixes #2639.
Switches the FAQ page from taking a stance on the issue to explicitly noting it as out of scope.
> docs: correct FAQ note about 0.x major versions

- lib/get-config.js
- package-lock.json
- package.json
Restore support for Windows absolute path in the `extends` configuration option by using `import-from-esm` to load the referenced module.
Following the changes in #3037, [a user encountered an `ERR_UNSUPPORTED_ESM_URL_SCHEME` error](https://github.com/semantic-release/commit-analyzer/pull/537#issuecomment-1800309172) because [using `resolve-from`](https://github.com/semantic-release/semantic-release/pull/3037/files#diff-3d464ef33ea10184a2faab420f7980eaedb53ad4c88aeb788fbc5a932eeebf16R36) [does not return an URL](https://github.com/sindresorhus/resolve-from/blob/main/index.js#L29C2-L33C5), and `import` then considers `C:/` to be an URL scheme (like `file://`) and returns the encountered error.
Since there are no Windows-specific tests on this repository and the test pipeline doesn't run on …
> fix: support windows absolute extends

- README.md
> docs: fix broken link to 'sentimental versioning' resource

- package-lock.json
- package.json
Reverts semantic-release/semantic-release#3072
because it is breaking users that have configure using a `release.config.js` as reported in https://github.com/semantic-release/semantic-release/issues/3089
> Revert "fix(deps): update dependency cosmiconfig to v9"

- docs/developer-guide/js-api.md
Change `And object with lastRelease, ...` to `An object with lastRelease, ...`
and 
`The list of commit included...` to `The list of commit(s) included...`
> Docs: fix typo in JS API guide

- docs/usage/installation.md
…into terminal without editing after pressing the copy button
I frequent these docs and use semantic release in multiple projects, it's mildly annoying that whenever I click the copy button it comes with the '$' character that my terminal does not recognize. I think it would be a much better user experience if users could simply click the copy button and paste it into their terminal without any issues.
> docs: updated installation docs so that user can copy paste without error

- docs/extending/plugins-list.md
This plugin is for teams that like to avoid conventional commits, but do want to make use of the plugin ecosystem of semantic-release.
`semantic-release-pull-request-analyzer` replaces `analyzeCommits` and `generateNotes`, so that it can find the release-type based on merged pull request labels, instead of commit subjects.
> docs: add community plugin semantic-release-pull-request-analyzer

- lib/get-config.js
- package-lock.json
- package.json
read-pkg-up has been renamed into  read-package-up
https://github.com/sindresorhus/read-package-up/commit/1e22fad74d26bba3ea71fd34d2f9224cc5dd1b6b
> Rename dependency 'read-pkg-up' -> 'read-package-up'

- docs/recipes/ci-configurations/github-actions.md
Updated a URL for `GITHUB_TOKEN` documentation (which no longer describes how tokens are auto-generated for CI), and replaced it with another appropriate GitHub documentation URL.
> docs(ci-configurations): update github token URL

- docs/usage/configuration.md
**Context**
Following this [discussion](https://github.com/semantic-release/semantic-release/discussions/2439) last year, documentation note hasn't been added.
> docs(configuration): add micromatch note for branches configuration key

- docs/support/FAQ.md
realized this could be more clear from https://github.com/semantic-release/semantic-release/discussions/3362#discussioncomment-9843383
> docs(plugins): linked from faq about non-js projects to plugins list

- package-lock.json
- package.json
- test/e2e.test.js
This PR updates the minimum version bound of the `@semantic-release/github` plugin from `v10.0.0` to [v11.0.0](https://github.com/semantic-release/github/releases/tag/v11.0.0)
> fix(deps): update `@semantic-release/github` to `v11.0.0`

- lib/definitions/errors.js
Updated error messages in `EMAINTENANCEBRANCHES`, `ERELEASEBRANCHES`, and `EPRERELEASEBRANCH` to explicitly state that branches must exist on the remote repository.
This change is necessary because it was confusing for developers configuring semantic-release who had not yet created the remote branches. By clearly stating that the branches must exist on the remote, we help prevent misconfigurations and improve the user experience.
There was an issue for this and also a stale PR, but maybe now is finally the time where we can merge this to improve the developer experience.
> feat: clarify branch existence requirement in error messages

- docs/extending/plugins-list.md
Hi,
We (at Covage) created a new plugin for semantic-release to better fit internal use-case of Poetry.
The sole purpose of this plugin is to update the version field inside the `pyproject.toml`.
The benefits of this plugin over [semantic-release-pypi](https://github.com/abichinger/semantic-release-pypi) : 
- More fitted and focused to the use-case of a private package registry. 
- It only depend on Node.js and does not require Python in the CI pipeline container.
Please see the details and source code of this plugin : https://github.com/covage/semantic-release-poetry-plugin 
This plugin is published on NPM : https://www.npmjs.com/package/@covage/semantic-release-poetry-plugin
We now use this plugin instead of a bumpversion.sh script in our private code repositories.
> docs(plugin): add @covage/semantic-release-poetry-plugin

- docs/recipes/ci-configurations/github-actions.md
The GitHub actions used in the docs were outdated.
> docs: update github-actions docs actions

- docs/recipes/ci-configurations/github-actions.md
I noticed the existing link to the ["Configuring a Workflow"](https://help.github.com/en/articles/configuring-a-workflow) page 404's. I have replaced it with the ["Workflow syntax for GitHub Actions"](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions) page, which has all possible configuration options for a GHA workflow.
> fix(docs): Fix broken GitHub Actions link

- README.md
Angular has moved their commit message guidelines from a section of the README into a separate markdown file. This PR fixes the link to point at the correct location.
> docs: update angular commit message guidelines link

- package-lock.json
- package.json
to a version that declares peer-deendency compatibility with `marked` v15
this will force an update of `marked-terminal` in projects with stale lockfiles, like #3725 or #3726
> fix(deps): raise the minimum of the defined range for `marked-terminal`

- package-lock.json
- package.json
- closes https://github.com/semantic-release/semantic-release/issues/3777
- Before the release of [npm@10.9.3](https://github.com/npm/cli/releases/tag/v10.9.3), installing `semantic-release` reported a low severity vulnerability
- For such existing projects, `npm audit fix` may continue to report that the vulnerability cannot be fixed and refers to https://github.com/advisories/GHSA-v6h2-p8h4-qcjw (CVE-2025-5889 - brace-expansion Regular Expression Denial of Service vulnerability)
- Since the release of [npm@10.9.3](https://github.com/npm/cli/releases/tag/v10.9.3), a complete new installation of `semantic-release` reports no vulnerability
- Uninstalling and re-installing `semantic-release` also works around the issue
- Executing `npm ci` in this repo …
> fix(deps): update @semantic-release/npm to ^12.0.2

- lib/branches/get-tags.js
- lib/git.js
- lib/utils.js
- test/git.test.js
- test/utils.test.js
I’ve identified that retrieving tags and their notes is a performance issue, especially in large repositories with hundreds of tags. 
The current implementation calls git notes twice (due to backward compatibility for some older semantic-release versions) for each tag, sequentially. Here is the problematic part https://github.com/semantic-release/semantic-release/blob/master/lib/branches/get-tags.js#L24
I found out that notes for each tag can be obtained in a single command, which takes only a few milliseconds. Here is the command I used (should cover the older notes refs as well):
```sh
git log --tags="*" --decorate-refs="refs/tags/*" --no-walk --format="%d%x09%N" --notes="refs/notes/semantic-release*"
```
And the example output for this repository:
```
(tag: v24.2.5)	
(tag: v24.2.4) …
```
> perf(get-tags.js): bulk get for tags notes
